repos:
  - repo: local
    hooks:
      - id: Update dependencies
        name: Update dependencies
        entry: python -m mky_utils.update_dependencies
        language: system
        files: ^(requirements.txt|pyproject.toml)$